---
- hosts: test0
  remote_user: root
  tasks:
   - name: test connection
     ping:

   - name: disable firewalld service on system start up
     systemd:
       name: firewalld
       enabled: no

   - name: stop firewalld service
     systemd:
       name: firewalld
       state: stopped

   - name: installing set of packages
     yum:
       name: "{{item}}"
       state: latest
     with_items:
       - mc
       - nano
       - iptables-services
       - docker
       - python-docker-py

   - name: enable services on system start up
     systemd:
       name: "{{item}}"
       enabled: yes
     with_items:
       - iptables
       - ip6tables
       - docker

   - name: start services
     systemd:
       name: "{{item}}"
       state: started
     with_items:
       - iptables
       - ip6tables
       - docker

   - name: copy Dockerfile
     copy:
       src: "{{item}}"
       dest: /tmp/skyeng/
       owner: root
       group: root
       mode: 0644
     with_items:
       - Dockerfile
       - start.sh
       - resources.sh

   - name: build a docker image
     docker_image:
       path: /tmp/skyeng
       name: saburovga/skyeng
       state: present
       force: no

   - name: Start a container
     docker_container:
       name: skyeng
       image: saburovga/skyeng
       published_ports: 
        - "8080:80" 
        - "2222:22"