---
- hosts: test0
  remote_user: root

  pre_tasks:
   - name: disable firewalld service on system start up
     systemd:
       name: firewalld
       enabled: no

   - name: stop firewalld service
     systemd:
       name: firewalld
       state: stopped

   - name: installing set of packages
     yum:
       name: "{{item}}"
       state: latest
     with_items:
       - mc
       - nano
       - iptables-services
       - docker
       - python-docker-py

   - name: enable services on system start up
     systemd:
       name: "{{item}}"
       enabled: yes
     with_items:
       - iptables
       - ip6tables
       - docker

   - name: start services
     systemd:
       name: "{{item}}"
       state: started
     with_items:
       - iptables
       - ip6tables
       - docker

  roles:
    - {role: docker}
